name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/snipTube/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Build the chromium based extension and zip it
        run: pnpm build:plasmo --zip
      - name: Build the safari based extension and zip it
        run: pnpm build:plasmo --target=safari-mv2 --zip

      - name: Upload ChromeExtension to release
        uses: Shopify/upload-to-release@07611424e04f1475ddf550e1c0dd650b867d5467
        with:
          args: build/chrome-mv3-prod.zip
          path: build/chrome-mv3-prod.zip
          name: ChromeExtension.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SafariExtension to release
        uses: Shopify/upload-to-release@07611424e04f1475ddf550e1c0dd650b867d5467
        with:
          args: build/safari-mv2-prod.zip
          path: build/safari-mv2-prod.zip
          name: SafariExtension.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload EdgeExtension to release
        uses: Shopify/upload-to-release@07611424e04f1475ddf550e1c0dd650b867d5467
        with:
          args: build/chrome-mv3-prod.zip
          path: build/chrome-mv3-prod.zip
          name: EdgeExtension.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.PUBLISHING_KEYS }}
          # chrome-file: "build/myext_chromium_${{ env.EXT_VERSION }}.zip"
          # edge-file: "edge/myext_edge_${{ env.EXT_VERSION }}.zip"
          # edge-notes: "This is a test submission"
          # version-file: "src/manifest.json"
          verbose: true
